---
title: "presentation graphs"
output: html_document
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(rmarkdown)
library(tidyverse)
library(tidymodels)
library(palmerpenguins)
library(knitr)
library(revealjs)
library(broom)
library(ggridges)
library(here)
library(gt)
```

```{r read-data, include = FALSE}
imdb <- read.csv(file = here("data/imdb-merge.csv"))
```

```{r average-rating, echo = FALSE}
imdb %>%
  ggplot(aes(x = avg_vote)) +
  geom_histogram(binwidth = 0.5) +
  labs(
    title = "Distribution of Average Rating",
    x = "Average Rating",
    y = "Frequency"
  ) +
  theme_minimal()
```

```{r average-rating-country-table, echo = FALSE}
imdb_country <- imdb %>%
  separate_rows(country, sep = "\\,") %>%
  mutate(country = case_when(
    country == "HongKong" ~ "Hong Kong",
    TRUE ~ country)) %>%
  filter(
     country %in% c("USA", "France", "UK", "India", "Italy", "Germany", "Japan", "Canada", "Spain", "Hong Kong", "Turkey", "Belgium")
   ) %>%
  distinct()

imdb_country %>%
  group_by(country) %>%
  summarise(
    mean_rating = mean(avg_vote, na.rm = TRUE),
    median_rating = median(avg_vote, na.rm = TRUE)
    ) %>%
  arrange(desc(mean_rating)) %>%
  gt() %>%
  cols_label(
    country = "Country",
    mean_rating = "Mean Rating",
    median_rating = "Median Rating"
  )
```

```{r average-rating-country, echo = FALSE}
imdb_country %>%
  ggplot(aes(x = avg_vote, y = country, fill = country)) +
  geom_density_ridges(alpha = 0.5, show.legend = FALSE) +
  labs(
    title = "Distribution of IMDb Average Ratings",
    subtitle = "for top 12 countries who have produced the most films",
    x = "Average rating",
    y = NULL
  ) +
  theme_minimal()
```

```{r country-us-rating, echo = FALSE, warning = FALSE}

imdb_country_longer <- imdb_country %>%
  pivot_longer(cols = c(us_rating, non_us_rating), names_to = "us_or_not", values_to = "rating")

imdb_country_longer %>%
  ggplot(aes(x = rating, fill = us_or_not)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ country) +
  labs(
    title = "Average Rating by US or non-US users",
    subtitle = "by country",
    x = "Average Rating",
    y = "Density",
    fill = NULL
  ) +
  theme_minimal()

imdb_country %>%
  group_by(country) %>%
  summarise(
    us_avg = mean(us_rating, na.rm = TRUE),
    non_us_avg = mean(non_us_rating)
  )
```

```{r data-analysis-prop-us-country}
imdb_country %>%
  filter(country %in% c("USA", "France", "UK", "India", "Italy", "Germany", "Japan", "Canada", "Spain", "Hong Kong", "Turkey", "Belgium")) %>%
  ggplot(aes(x = prop_us_votes, y = avg_vote, color = country)) +
  geom_point(alpha = 0.3) +
  stat_smooth(method = "lm", se = FALSE, color = "black") +
  facet_wrap(~country)
```

```{r data-analysis-genre}
imdb_genre <- imdb %>%
  separate_rows(genre, sep = "\\,") %>%
  mutate(genre = case_when(
    genre == "SciFi" ~ "Sci Fi",
    genre == "FilmNoir" ~ "Film Noir",
    TRUE ~ genre)) %>%
  distinct()

imdb_genre %>%
  filter(
    genre %in% c("Drama", "Comedy", "Action", "Horror", "Crime", "Thriller", "Romance", "Adventure", "Mystery", "Family", "Animation")
  ) %>%
  ggplot(aes(x = us_rating, y = genre, fill = genre)) +
  geom_density_ridges(alpha = 0.5, show.legend = FALSE) +
  labs(
    title = "Distribution of US IMDb Average Rating by Genre",
    x = "Average Rating",
    y = "Genre"
  )
imdb_genre %>%
  filter(
    genre %in% c("Drama", "Comedy", "Action", "Horror", "Crime", "Thriller", "Romance", "Adventure", "Mystery", "Family", "Animation")
  ) %>%
  group_by(genre) %>%
  summarise(rating = median(us_rating, na.rm = TRUE)) %>%
  arrange(desc(rating))
```


```{r top-genre}
imdb_genre %>%
  filter(str_detect(country, "Italy"))  %>%
  group_by(genre) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n)) %>%
  arrange(desc(n))
imdb_genre %>%
  filter(str_detect(country, "Japan")) %>%
  group_by(genre) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n)) %>%
  arrange(desc(n))
imdb_genre %>%
  filter(str_detect(country, "USA")) %>%
  group_by(genre) %>%
  summarise(n = n()) %>%
  mutate(prop = n / sum(n)) %>%
  arrange(desc(n))
```

```{r genre-linear-regression, echo = FALSE}
imdb_genre_regression <- imdb_genre %>%
  filter(genre %in% c("Drama", "Comedy", "Horror", "Animation", "Action", "Crime"))
imdb_genre_reg_US <- linear_reg() %>%
  set_engine("lm") %>%
  fit(us_rating ~ genre, data = imdb_genre_regression)
  tidy(imdb_genre_reg_US)
imdb_genre_reg_nonUS <- linear_reg() %>%
  set_engine("lm") %>%
  fit(non_us_rating ~ genre, data = imdb_genre_regression)
  tidy(imdb_genre_reg_nonUS)
```

```{r genre-linear-regression2}
imdb_genre_longer <- imdb_genre %>%
  pivot_longer(cols = c(us_rating, non_us_rating), names_to = "us_or_not", values_to = "rating") %>%
  filter(genre %in% c("Drama", "Comedy", "Horror", "Animation", "Action", "Crime"))

linear_reg() %>%
  set_engine("lm") %>%
  fit(rating ~ genre + us_or_not, data = imdb_genre_longer) %>%
  tidy()
  
  
```

```{r income}
imdb_longer <- imdb %>%
  pivot_longer(cols = c(us_rating, non_us_rating), names_to = "us_or_not", values_to = "rating")
   
imdb_longer %>%
  ggplot(aes(x = usa_gross_income, y = rating, color = us_or_not)) +
  geom_point(alpha = 0.3) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    title = "Average Rating vs. US Gross Income",
    x = "US Gross Income",
    y = "Average Rating",
    color = NULL
  ) +
  stat_smooth(method = "lm", se = FALSE) + 
  theme_minimal() +
  scale_x_continuous(breaks = c(0, 250000000, 500000000, 750000000), labels = c("$0", "$250M", "$500M", "$750M"))
  
```

```{r income-regression}

imdb_income_country_regression <- linear_reg() %>%
  fit(us_rating ~ log(worlwide_gross_income) + country, data = imdb_country)
  tidy(imdb_income_country_regression)
  
imdb_income_regression <- linear_reg() %>%
  fit(us_rating ~ log(worlwide_gross_income), data = imdb_country)
  
glance(imdb_income_country_regression)$adj.r.squared
glance(imdb_income_regression)$adj.r.squared
```

```{r residuals}
imdb_country_log <- imdb_country %>%
  mutate(log_worlwide_income = log(worlwide_gross_income)) 

imdb_income_regression_bug <- linear_reg() %>%
  fit(us_rating ~ log_worlwide_income, data = imdb_country_log)

imdb_income_regression_aug <- augment(imdb_income_regression_bug$fit)

ggplot(data = imdb_income_regression_aug) +
  geom_jitter(aes(x = .fitted, y = .resid)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    title = "Residual plot of log(us avg rating) vs. worldwide income",
    x = "Predicted Values",
    y = "Residuals"
  )
```